apiVersion: v1
kind: Pod
metadata:
  name: testpod
  
spec:
  containers:
  - name: myapp
    image: nginx:alpine
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
