apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web 
spec:
  selector:
    matchLabels:
      app: web
  serviceName: "web"  # prefix for the pod
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        emptyDir: {}  ## Local Volume
---
# Headless Service for StatefulSet
apiVersion: v1
kind: Service
Metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  clusterIP: None